baseURL = "/"
languageCode = 'en-us'
title = 'Tabit'
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[build]
  useResourceCacheWhen = "never"
  
[security]
  [security.funcs]
    getenv = ["^SUPABASE_"]
