baseURL = "/"
languageCode = 'en-us'
title = 'Tabit'
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[build]
  useResourceCacheWhen = "never"
  
[security]
  [security.funcs]
    getenv = ["^SUPABASE_", "NETLIFY_DEV"]

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"