# Netlify configuration file

[build]
  command = "deno task prod"
  publish = "public"
  functions = "functions"

[build.environment]
  DENO_VERSION = "1.37.1"
  GO_VERSION = "1.21"

[context.production]
  command = "deno task prod"

[context.deploy-preview]
  command = "deno task prod"

[context.branch-deploy]
  command = "deno task prod"

[dev]
  command = "deno task dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = true


[functions]
  included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


